### ISSUE TITLE
Compile error: "font file is missing"

### ISSUE THREAD

**Issue by Bluebird45** [dunnker/tetris-piston#3]
Hi, I just now downloaded tetris-piston, ran "cargo update" and then "cargo run". This is the result:

<pre>
$ cargo run
Running `target/debug/tetris-piston` thread '<main>' panicked at 'Font file is missing,
or does not exist in the current path.', src/main.rs:270 note: Run with `RUST_BACKTRACE=1`
for a backtrace. Process didn't exit successfully: `target/debug/tetris-piston`
(exit code: 101)
</pre>

Here is the backtrace:

<pre>
$ RUST_BACKTRACE=1 cargo run
     Running `target/debug/tetris-piston`
thread '<main>' panicked at 'Font file is missing, or does not exist in the current path.', src/main.rs:270
stack backtrace:
   1:     0x7f4f1c5f6b90 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7f4f1c5f942b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7f4f1c5f9098 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x7f4f1c5f001c - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x7f4f1c3eff57 - sys_common::unwind::begin_unwind::h5278559957863188872
                        at ../src/libstd/sys/common/unwind/mod.rs:219
   6:     0x7f4f1c3f85fe - start_app::ha9af01577e6edaefo0a
                        at /home/user/projects/tetris-piston/<std macros>:3
   7:     0x7f4f1c3f8368 - main::h8524402bbdbd8c24i0a
                        at src/main.rs:253
   8:     0x7f4f1c5f8cf4 - sys_common::unwind::try::try_fn::h14622312129452522850
   9:     0x7f4f1c5f60cb - __rust_try
  10:     0x7f4f1c5f878b - rt::lang_start::h0ba42f7a8c46a626rKz
  11:     0x7f4f1c3f89d9 - main
  12:     0x7f4f1b50ab44 - __libc_start_main
  13:     0x7f4f1c3bd7d8 - <unknown>
  14:                0x0 - <unknown>
Process didn't exit successfully: `target/debug/tetris-piston` (exit code: 101)
</pre>

**Comment by dunnker** [comment]
I don't have time to look at it just now, but the error is likely because the font file is not found in the current folder with the binary. You may have to copy the font file to the target folder where cargo creates the binary.

**Comment by Bluebird45** [comment]
Copying it there does not resolve the error.

I'm a student of Rust so I'm not clear on what the following code in main.rs does. Could I ask you to tell me what it is intended to do, because that is where the problem is.

```
265    let font_path = match OpenOptions::new().open("FiraMono-Bold.ttf") {
266        Ok(_) => Path::new("FiraMono-Bold.ttf"),
267        Err(_) => {
268            match OpenOptions::new().open("src/FiraMono-Bold.ttf") {
269                Ok(_) => Path::new("src/FiraMono-Bold.ttf"),
270                Err(_) => panic!("Font file is missing, or does not exist in the current path."),
271            }
272        }
273    };
```

**Comment by dunnker** [comment]
I believe it is trying to open the font file in the current directory. If the result of opening the file is "Ok" then font_path is assigned to the name of the file. If the result is Err, then it will try to open the file in the "src" sub-directory, again checking for Ok or Err.

You could try copying the font file into the src sub-folder to see if that works?
...it may also be possible that the font file cannot be opened due to a permissions issue, or it's marked read-only?

**Comment by Bluebird45** [comment]
I should have noted for completeness that this is Linux x64, with Rust 1.8 under rustup. It is the default file system and there is no reason to suspect permissions.

The font file was already in the src folder.

Maybe a newer dependency has broken something? 

I note that there were many updates when I ran "cargo update". The initial cloning of tetris-piston did not build but exited with an error when it got to compiling the fs2 module. Cargo update replaced fs2 with a newer version and so resolved that error.

In case the font file itself was the problem, I replaced it with the latest one.

Any ideas?

**Comment by dunnker** [comment]
I just tested it under Ubuntu with Rust 1.5 and it worked fine.
I will try with Rust 1.8 and let you know

**Comment by dunnker** [comment]
With Rust 1.8 it fails to build the fs2 crate, so I am not able to build at the moment...
Nevermind I see your comments now about building. Will try again shortly

**Comment by dunnker** [comment]
I was able to see the error in version 1.8
I've committed a fix for the issue. It appears that OpenOptions requires at least to invoke "read" before "open" in the latest version of rust. If you sync the latest changes it should work for you now.

**Comment by Bluebird45** [comment]
I just confirmed that a fresh download of tetris-piston does compile, and runs with no problem, using Rust 1.5.

For anyone who is interested, you can use Rustup to download an earlier Rust as follows:

Look at the [Rust archive](http://static.rust-lang.org/dist/index.html) (scroll down) to find the date when the target version was a nightly, then give a command of the form:

<pre>
rustup update nightly-2015-10-28
</pre>

(That will bring down Rust 1.5)

EDIT: I missed your previous comment (duh), so I'm not sure if I <b>was</b> reproducing the fact that it worked for you under Rust 1.5. However, I can now confirm that the bug is fixed.
